### ISSUE TITLE
`Program` deployment and associated `register_program` contract registry predicate.

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/essential-node#148]
Once the new program `Predicate` type is ready to land with the updated `Program` DAG model, the contract registry should be updated in the node to allow `Solution`s to register `Program`s independently of `Predicate`s.

`Program`s can be stored using a unique key within the existing contract registry.

`Program`s will need to be deployed either in the same `Solution` that their dependent `Predicate`(s) are deployed in, or in any earlier `Solution`.

The contract registry mutation for deploying a program will likely look something like this:

```yaml
key: [2, <program-ca>]
value: [len_bytes, <program-bytecode-padded>]
```

where `2` is the `programs` storage prefix within the contract registry.

## Validation

Program deployment validation will involve ensuring:

1. The content address that appears in the key matches the actual program content address (i.e. `sha256` of the program bytecode).
2. The length in bytes does not exceed `Program::MAX_SIZE`.

**Comment by freesig** [comment]
I think the program registry should be a separate contract as it's kind of unrelated to the contract registry. Contracts are sort of built on top of programs but that might not be the only usecase for programs.
