### ISSUE TITLE
Validation: Represent success in database

### ISSUE THREAD

**Issue by supiket** [essential-contributions/essential-node#67]
Currently if validation fails, the block is added to `failed_blocks` table but passing validation has no information in the database.

**Comment by freesig** [comment]
I think this can be deduced by the block not being in the `yet_to_be_validated` table or the `failed_blocks` table. Is there other info we should store though like gas usage or something?

**Comment by supiket** [comment]
I think we were talking about having a shortcut to the validation result of a block, but with tracing and the tables you mentioned in your comment, looks like this is not really needed. If this becomes an issue again, we can come back to it.
